# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: server
steps:
- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
    connectedServiceName: 'DevOps Connection'
    UpstreamJob: 'Job'
- task: ServiceNow-DevOps-Server-Artifact-Registration@1
  inputs:
    connectedServiceName: 'DevOps Connection'
    artifactRegistrationPayload: |
      {
            “artifacts”: [
            {
                “name”: “globes.war”,
                “repositoryName”: “”,
                “version”:  “1.$(Build.BuildId)”,
                “semanticVersion”: “1.$(Build.BuildId).0”
             }]}
    artifactToolIdExists: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop   

